export const starters = [
  'I am building a support triage tool',
  'I want to make my coding agent safer',
  'I need to route tasks to different models',
]

const advice = {
  default: {
    fit: 'Poor fit',
    fitClass: 'red',
    verdict: 'Do not use Jev yet',
    headline: 'There is not enough operational detail to choose a credible Jev boundary.',
    summary: 'A product description alone does not reveal the repeated decision, the state available before it, or what happens when the model is uncertain. Supplying those facts is better than receiving a generic integration pattern.',
    decision: 'Which concrete recurring event should trigger one bounded decision?',
    questionType: 'choice',
    choices: ['act', 'defer', 'escalate'],
    stateFields: ['trigger_event', 'available_evidence', 'valid_actions'],
    jevOwns: 'Nothing yet—the decision boundary is still underspecified.',
    codeOwns: 'Identify the trigger, enumerate only valid outcomes, and define how success will be observed.',
    avoid: 'Do not add Jev as a general project advisor or ask it to invent the workflow.',
    threshold: 'No automation threshold until labelled examples show which probabilities correspond to acceptable error.',
    fallback: 'Keep the current deterministic or human process until a testable decision is isolated.',
    successTest: 'Collect 30–50 historical cases with the action that should have been taken and the observed result.',
    missingEvidence: ['What event triggers the decision?', 'What state is available at that moment?', 'What are the complete valid outcomes?', 'How will a correct decision be verified?'],
    referencePatterns: ['SemDecide: one semantic predicate with stable exit behavior.', 'Jev MCP: typed judgments exposed as a narrow tool rather than a general agent.'],
    steps: [
      'Name the state Jev should inspect and the finite answer space it should return.',
      'Keep a general LLM for open-ended reasoning, explanations, and unusual cases.',
      'Route low-confidence results to a stronger model or a human instead of forcing automation.',
    ],
    confidence: null,
  },
  support: {
    fit: 'Strong fit',
    fitClass: 'green',
    verdict: 'Use Jev',
    headline: 'Use Jev to route each incoming ticket—not to write the reply.',
    summary:
      'Use Jev as the first-pass router for repetitive support decisions. It can classify each ticket quickly, then reserve a full LLM for nuanced replies.',
    decision: 'Which team should handle this ticket?',
    questionType: 'choice',
    choices: ['billing', 'technical', 'sales', 'account'],
    stateFields: ['subject', 'message_body', 'customer_plan', 'recent_ticket_category'],
    jevOwns: 'Choose the owning queue and independently score explicit urgency.',
    codeOwns: 'Fetch customer context, enforce VIP/security overrides, assign the queue, and measure reassignment outcomes.',
    avoid: 'Do not let Jev compose the support response, diagnose an incident, or invent a department outside the configured queues.',
    threshold: 'Starting policy: auto-route only when the selected queue clears a threshold validated on historical tickets; otherwise send to triage.',
    fallback: 'Use the existing default queue when Jev is unavailable; send uncertain or no-match tickets to human triage.',
    successTest: 'Replay historical tickets and compare first-route accuracy, reassignment rate, and urgent-ticket recall against the current router.',
    missingEvidence: ['Current queue taxonomy and historical reassignment labels.', 'Which ticket categories require deterministic overrides.'],
    referencePatterns: ['SemDecide: stable typed routing with a distinct uncertain outcome.', 'Jev Review: screen first, then classify and prioritise.'],
    steps: [
      'Send the ticket text and recent customer context as the state.',
      'Ask Jev for department, urgency, and escalation as separate questions.',
      'Auto-route high-confidence results; send the middle band to review.',
    ],
    confidence: null,
  },
  safety: {
    fit: 'Strong fit',
    fitClass: 'green',
    verdict: 'Use Jev narrowly',
    headline: 'Use Jev as one risk signal before execution; deterministic permissions remain the authority.',
    summary:
      'Jev is useful as a fast safety gate before an agent executes a command. It should classify risk, not generate or rewrite the command.',
    decision: 'Is this command safe to execute automatically?',
    questionType: 'choice',
    choices: ['safe', 'needs_review', 'destructive'],
    stateFields: ['command', 'arguments', 'working_directory', 'requested_task', 'affected_resources'],
    jevOwns: 'Classify semantic risk and flag ambiguity that static rules cannot express.',
    codeOwns: 'Resolve exact targets, enforce allow/deny rules, request approval, execute, and verify the resulting state.',
    avoid: 'Do not let Jev authorize destructive, financial, credential, production, or privacy-sensitive actions by itself.',
    threshold: 'Starting policy: only the low-risk class may proceed, and only after deterministic checks pass; uncertainty always escalates.',
    fallback: 'Fail closed to review on timeout, malformed output, missing context, or disagreement with deterministic checks.',
    successTest: 'Evaluate on labelled safe, ambiguous, and destructive commands with emphasis on destructive-command recall and false allows.',
    missingEvidence: ['The deterministic permission rules already in place.', 'The cost of a false allow versus an unnecessary approval.'],
    referencePatterns: ['Agent Desktop: validate current UI targets before acting.', 'Jev Drone: ordinary code owns the safety reflex; Jev remains advisory.'],
    steps: [
      'Provide the command, working directory, and task context as the state.',
      'Block destructive decisions by default and show the user the exact command.',
      'Log the decision, confidence, and final human override for evaluation.',
    ],
    confidence: null,
  },
  routing: {
    fit: 'Strong fit',
    fitClass: 'green',
    verdict: 'Use Jev',
    headline: 'Use Jev to select the cheapest adequate execution tier for each task.',
    summary:
      'Use Jev as a cheap complexity classifier before the request reaches a model. It can keep simple work on a fast model and escalate only when needed.',
    decision: 'What level of reasoning does this task need?',
    questionType: 'choice',
    choices: ['fast', 'deep', 'research'],
    stateFields: ['user_request', 'tool_requirements', 'repo_size', 'risk_flags', 'recent_failed_attempts'],
    jevOwns: 'Choose the execution tier and return the distribution used by the escalation policy.',
    codeOwns: 'Maintain the model catalog, enforce capability constraints, execute the chosen route, and record task success.',
    avoid: 'Do not ask Jev to solve the coding task or choose from models that cannot satisfy its tool and context requirements.',
    threshold: 'Starting policy: accept the cheapest tier only when it wins clearly; route close distributions upward and retry failed work on a stronger tier.',
    fallback: 'Use the current default model when routing fails; never downgrade a task after a capability or safety requirement is detected.',
    successTest: 'Backtest against completed tasks using success, retries, latency, and cost—not agreement with the previous model choice.',
    missingEvidence: ['Available models and their hard capability limits.', 'A task-success signal independent of the routing decision.'],
    referencePatterns: ['Jev Codex Router: per-turn model and reasoning-depth selection.', 'Canny: verify completion independently instead of trusting the worker’s claim.'],
    steps: [
      'Define what each reasoning tier means in observable terms.',
      'Start with conservative escalation thresholds while collecting outcomes.',
      'Measure routing accuracy against task success, not just model preference.',
    ],
    confidence: null,
  },
  frontend: {
    fit: 'Promising fit',
    fitClass: 'amber',
    verdict: 'Use Jev narrowly',
    headline: 'Use Jev to choose the next design-quality gate—not to design the interface.',
    summary: 'For a frontend-design pipeline, Jev is useful after the agent has a concrete change and a finite set of checks. It can select whether the next gate is accessibility, responsive behavior, interaction state, visual polish, or human review; it should not invent the visual direction or replace browser verification.',
    decision: 'Which design-quality gate should run next for this frontend change?',
    questionType: 'choice',
    choices: ['accessibility', 'responsive', 'interaction', 'visual_polish', 'human_review'],
    stateFields: ['changed_surface', 'user_goal', 'viewport_states', 'interaction_states', 'known_constraints', 'diff_summary'],
    jevOwns: 'Select the next bounded review gate from the checks the pipeline supports.',
    codeOwns: 'Build the candidate gate list, run the selected check, capture browser evidence, and block release on hard failures.',
    avoid: 'Do not ask Jev to choose the brand direction, write CSS, judge an unrendered mockup, or declare the site finished without browser evidence.',
    threshold: 'Starting policy: auto-select a gate only above 0.8 confidence; otherwise run the required accessibility and responsive checks plus human review.',
    fallback: 'If Jev is uncertain or unavailable, run the deterministic baseline checks and escalate the design decision to the agent or reviewer.',
    successTest: 'Replay labelled frontend changes and compare Jev-selected gates with reviewer-identified defects and post-build browser failures.',
    missingEvidence: ['The pipeline’s actual gate catalog and hard-failure rules.', 'A labelled set of frontend changes showing which gate found the defect.', 'Browser screenshots or runtime checks for the changed surface.'],
    referencePatterns: ['Jev Review: use typed judgments to prioritise review attention, not to claim correctness.', 'Jev Ultrafast: observe the current structured state, choose from valid actions, then verify the result.', 'json-render: constrain generated UI to a known component and state catalog.'],
    steps: [
      'Represent the changed surface, user goal, viewport states, and interaction states as structured input.',
      'Ask Jev to choose one supported review gate, with human-review as an explicit option.',
      'Run the gate in the browser and keep the release blocked until its evidence is recorded.',
    ],
    confidence: null,
  },
}

export function pickAdvice(text) {
  const normalized = String(text || '').toLowerCase()
  if (normalized.includes('frontend') || normalized.includes('design pipeline') || normalized.includes('ui') || normalized.includes('website')) return advice.frontend
  if (normalized.includes('support') || normalized.includes('ticket')) return advice.support
  if (normalized.includes('safe') || normalized.includes('command') || normalized.includes('terminal'))
    return advice.safety
  if (normalized.includes('route') || normalized.includes('model')) return advice.routing
  return advice.default
}
